import { NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { calculateRouteScore, RouteData } from '@/lib/routingEngine';
import mapData from '@/data/stadium-map.json';

// Initialize SDK (picks up process.env.GEMINI_API_KEY)
const ai = new GoogleGenAI({});

export async function POST(req: Request) {
  try {
    const { message, gateCSurgeActive, needsAccess } = await req.json();

    // 1. Calculate best route using the backend engine logic
    const best = calculateRouteScore(mapData.routes as RouteData[], { requiresAccessibility: needsAccess }, gateCSurgeActive);
    
    if (!best) {
      return NextResponse.json({ error: "No valid route found." }, { status: 400 });
    }

    const routeDataResult = {
      path: [best.route.transit, best.route.gate, "Stadium Sector"],
      score: best.score,
      explanation: "" // Generated by Gemini
    };

    // 2. Prepare prompt context
    const contextStr = `
    User Request: "${message}"
    Calculated Best Route Name: ${best.route.name}
    Route Path: ${routeDataResult.path.join(' -> ')}
    Route Score: ${best.score} (lower is better)
    Is Route Accessible?: ${best.route.isAccessible}
    Gate C Surge Active?: ${gateCSurgeActive}
    Live Data Context: ${JSON.stringify(mapData, null, 2)}
    `;

    const systemPrompt = "You are FlowTwin 26, a helpful stadium assistant. Explain this calculated route to the fan in a reassuring tone, and translate the response to Spanish if requested. Do not hallucinate paths that aren't in the route path provided. Only explain the route details provided in the context.";
    
    // 3. Prompt Gemini
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `${systemPrompt}\n\nContext:\n${contextStr}`
    });

    const aiExplanation = response.text || "I found a great route for you.";
    routeDataResult.explanation = aiExplanation;

    return NextResponse.json({ routeData: routeDataResult });

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    return NextResponse.json({ error: error.message || "Failed to generate response" }, { status: 500 });
  }
}
